### ISSUE TITLE
Убрать лишний регекс

### ISSUE THREAD

**Issue by pingvin1308** [IlyaEliseev/Homeworks#1]
https://github.com/IlyaEliseev/Homeworks/blob/a19057c297610b6479db7583c4cde697478dde44/Homeworks.CleanetCode.TypesBranchesAndLoops/Homework.GuessingNumberGame/Program.cs#L9

Оу синьер да вы знаток регекс паттернов :)

Клевая штука, но катастрофически усложняет воспринимаемость кода (когнитивная сложность).
Пользовать регексом не табу, но делать это нужно только при острой необходимости.

К примеру проверку имени сделал здорово, хотя если бы была локализация/языки, я бы посмотрел бы на результат :)
Вероятно русские символы не пройдут.

В общем предлагаю убрать регекс для проверки подтверждения и сделать просто сравнение с 'y'.
Ввод пользователя можно проверить на null и пустоту. И перед проверкой с 'y', вызвать .Trim().ToLower().
Тогда у тебя будет однозначно понятный способ сравнивать без регекса. 

Немногие могут легко читать регекс, по этому приходится лезть в гугл за подсказками. 
Это как минимум удлиняет процесс код ревью в команде.

**Comment by IlyaEliseev** [comment]
Ок. Изначально просто проверял на null и whitespace) Так как в задании не было точных критериев валидации решил попробовать регекс.
