### ISSUE TITLE
Не сравнивай буллевое значение в If

### ISSUE THREAD

**Issue by Rerinow** [IlyaEliseev/Homeworks#8]
Используй просто If(UserSession.Login)
https://github.com/IlyaEliseev/Homeworks/blob/49c826dd5c59ac2930d778f6d060714a2f174024/CleanetCode.TodoList/CleanetCode.TodoList.CLI/CleanetCode.TodoList.CLI/Operations/CompleteTaskOperation.cs#L12

**Comment by IlyaEliseev** [comment]
Спасибо поправил.
